// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBe10c6UlfR2js8TliCCEZfyKLtskEtiOs',
    appId: '1:597205789236:web:2fe5ff56e48a71f24eb861',
    messagingSenderId: '597205789236',
    projectId: 'locket-widget-7f13d',
    authDomain: 'locket-widget-7f13d.firebaseapp.com',
    storageBucket: 'locket-widget-7f13d.appspot.com',
    measurementId: 'G-WTMT9K33TY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9ofAhel40MX-YDmY4vYxpyZ9_0nidc3I',
    appId: '1:597205789236:android:946225ed2d90e7e54eb861',
    messagingSenderId: '597205789236',
    projectId: 'locket-widget-7f13d',
    storageBucket: 'locket-widget-7f13d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpmaadHAL_Ss-TEAXAeuMTM8pUdY6YwaM',
    appId: '1:597205789236:ios:3727d5c3473c99234eb861',
    messagingSenderId: '597205789236',
    projectId: 'locket-widget-7f13d',
    storageBucket: 'locket-widget-7f13d.appspot.com',
    iosBundleId: 'com.example.locketWidget',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBe10c6UlfR2js8TliCCEZfyKLtskEtiOs',
    appId: '1:597205789236:web:d722537e622a9da94eb861',
    messagingSenderId: '597205789236',
    projectId: 'locket-widget-7f13d',
    authDomain: 'locket-widget-7f13d.firebaseapp.com',
    storageBucket: 'locket-widget-7f13d.appspot.com',
    measurementId: 'G-9CHRC7JRHW',
  );
}
